apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    component: ws_server_blue_green
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: ws_server_blue_green
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: ws_server_blue_green
    spec:
      containers:
        - name: ws-server-blue-green
          image: "{{ .Values.ws_server_blue_green.image.repository }}:{{ .Values.ws_server_blue_green.image.tag }}"
          ports:
            - containerPort: {{ .Values.ws_server_blue_green.containerPort }}