replicaCount: 1

ws_server_blue_green:
  image:
    repository: 127.0.0.1:5000/ws-server-blue-green
    tag: latest
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 32000
  containerPort: 8000

ingress:
  enabled: true
  hosts:
    - host: ws_server_blue_green.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            ws_server_blue_green:
              service:
                name: ws_server_blue_green
                port:
                  number: 8000
